name = "seomnissiah-api"
main = "server/server.js"
compatibility_date = "2024-01-28"

[build]
command = "npm install"
watch_dir = "server"

[env.production]
name = "seomnissiah-api-prod"

[[kv_namespaces]]
binding = "SESSIONS"
id = "sessions"
